apiVersion: v1
kind: Secret
metadata:
  name: pxc-backup-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_ID: {{ .Values.oidc.centralOIDC.clientId | quote}}
  {{- if .Values.oidc.centralOIDC.frontendUrl }}
  OIDC_ENDPOINT: {{ printf "%srealms/master" .Values.oidc.centralOIDC.frontendUrl }}
  {{- else }}
  OIDC_ENDPOINT: "http://pxcentral-keycloak-http/auth/realms/master"
  {{- end }}
  {{ if .Values.oidc.centralOIDC.cert }}
  OIDC_CERT: {{ .Values.oidc.centralOIDC.cert | quote}}
  {{- end}}
