apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: px-hook-predelete-nodelabel
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
{{ if ge .Capabilities.KubeVersion.Minor "8" }}
  backoffLimit: 0
{{ else }}
  activeDeadlineSeconds: 30  
{{ end }}
  template:
    spec:
      serviceAccountName: tiller
      restartPolicy: Never
      containers:
      - name: pre-delete-job
        image: "lachlanevenson/k8s-kubectl:{{ template "px.kubernetesVersion" . }}"
        args: ['label','nodes','--all','px/enabled=remove','--overwrite']