kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  namespace: {{ .Values.namespace }} 
  labels:
{{- include "px-backup.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  namespace: {{ .Values.namespace }} 
  labels:
{{- include "px-backup.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }} 
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io