{{/* Setting defaults if they are omitted. */}}
{{- $customRegistryEnabled := .Values.images.customRegistryEnabled | default false }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pxcentral-post-install-hook
  namespace: {{ .Values.namespace }}
  labels:
    name: pxcentral-post-install-hook
    app.kubernetes.io/component: pxcentral-post-install-hook
{{- include "px-backup.labels" . | nindent 4 }}
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pxbackup/enabled
                operator: NotIn
                values:
                - "false"
      serviceAccountName: pxcentral-onprem-job
      containers:
      - name: pxcentral-post-setup
        image: {{ printf "%s/%s/%s:%s" .Values.images.registry .Values.images.repo .Values.images.postSetupImage.imageName .Values.images.postSetupImage.tag }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
        env:
          - name: LOG_LEVEL
            value: INFO
          - name: PXC_NAMESPACE
            value: {{ .Values.namespace }}
        command: ["python",  "/pxcentral-post-install/pxc-post-setup.py"]
      imagePullSecrets:
        - name: {{ .Values.images.pullSecrets }}
      restartPolicy: Never
  backoffLimit: 5
  activeDeadlineSeconds: 2400
