apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: px-etcd-data-px-backup-etcd-0-snapshot
  namespace: portworx
spec:
  persistentVolumeClaimName: pxc-etcd-data-pxc-backup-etcd-0
---
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: px-etcd-data-px-backup-etcd-1-snapshot
  namespace: portworx
spec:
  persistentVolumeClaimName: pxc-etcd-data-pxc-backup-etcd-1
---
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: px-etcd-data-px-backup-etcd-2-snapshot
  namespace: portworx
spec:
  persistentVolumeClaimName: pxc-etcd-data-pxc-backup-etcd-2
---
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pxcentral-keycloak-postgresql-0-snapshot
  namespace: portworx
spec:
  persistentVolumeClaimName: pxc-keycloak-data-pxc-keycloak-postgresql-0
---
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: theme-pxcentral-keycloak-0-snapshot
  namespace: portworx
spec:
  persistentVolumeClaimName: theme-pxc-keycloak-0
---
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pxcentral-mysql-pvc-snapshot
  namespace: portworx
spec:
  persistentVolumeClaimName: pxc-mysql-pvc
---
