{{/* Setting defaults if they are omitted. */}}
{{- $lsEnabled := .Values.pxlicenseserver.enabled | default false -}}
{{- $licenseServerSecret := (lookup "v1" "Secret" .Release.Namespace "px-license-secret") | default dict }}
{{- $licenseServerSecretData := (get $licenseServerSecret "data") | default dict }}
{{- $licensePassword := (get $licenseServerSecretData "PX_LICENSE_PASSWORD" | b64dec | default (.Values.pxlicenseserver.adminUserPassword | include "nonEmptyOrDefault")) }}
{{- if eq $lsEnabled true }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: px-license-server
{{- include "px-central.labels" . | nindent 4 }}
  name: px-license-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PX_LICENSE_USER: {{ .Values.pxlicenseserver.adminUserName | quote}}
  PX_LICENSE_PASSWORD: {{  $licensePassword | quote}}
{{- end -}}