{{- $isOpenshiftCluster := .Capabilities.APIVersions.Has "apps.openshift.io/v1" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: px-backup-mongodb-pre-upgrade-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    name: pxcentral-pre-upgrade-hook
    app.kubernetes.io/component: pxcentral-pre-upgrade-hook
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "get", "list", "watch", "create", "update"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["delete", "get", "list", "watch", "update", "create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "create", "delete", "update", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "create", "delete", "update", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "update", "get", "patch", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: px-backup-mongodb-pre-upgrade-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    name: pxcentral-pre-upgrade-hook
    app.kubernetes.io/component: pxcentral-pre-upgrade-hook
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: px-backup-mongodb-pre-upgrade-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pre-upgrade-log-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    name: pxcentral-pre-upgrade-hook
    app.kubernetes.io/component: pxcentral-pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistentStorage.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pre-upgrade-dump-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    name: pxcentral-pre-upgrade-hook
    app.kubernetes.io/component: pxcentral-pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: {{ .Values.persistentStorage.storageClassName }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-upgrade-check
  namespace: {{ .Release.Namespace }}
  labels:
    name: pxcentral-pre-upgrade-hook
    app.kubernetes.io/component: pxcentral-pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-completed
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      {{- if $isOpenshiftCluster}}
      {{- else }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              {{- if .Values.nodeAffinityLabel }}
              - key: {{ .Values.nodeAffinityLabel }}
                operator: Exists
              {{- else }}
              - key: pxbackup/enabled
                operator: NotIn
                values:
                - "false"
              {{- end }}
      initContainers:
        - name: init-log-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /logs && chmod -R 777 /logs"]
          volumeMounts:
            - name: log-volume
              mountPath: /logs
        - name: init-dump-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /dumps && chmod -R 777 /dumps"]
          volumeMounts:
            - name: dump-volume
              mountPath: /dumps
      containers:
        - name: pxbackup-mongodb-upgrade
          image: {{ printf "%s/%s/%s:%s" .Values.images.preUpgradeHookImage.registry .Values.images.preUpgradeHookImage.repo .Values.images.preUpgradeHookImage.imageName .Values.images.preUpgradeHookImage.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command: ["python", "/pxcentral-pre-upgrade/pxc-pre-upgrade.py"]
          env:
            - name: STATEFULSET_NAME
              value: pxc-backup-mongodb
            - name: NAMESPACE
              value: {{ .Release.Namespace }}  
            - name: TARGET_VERSION
              value: {{ .Values.images.mongodbImage.tag }}
            - name: K8S_SERVICE_NAME
              value: pxc-backup-mongodb-headless
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_ROOT_USERNAME
              value: root
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-password
                  name: pxc-backup-mongodb
            - name: MYSQL_STATEFULSET_NAME
              value: pxcentral-mysql
            - name: MYSQL_ROOT_USERNAME
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: pxcentral-mysql-secret
            - name: JOB_TIMEOUT_SECONDS
              value: "600"
            - name: MONGODB_IMAGES
              value: >
                {
                  "registry": "{{ .Values.mongodbImages.registry }}",
                  "repo": "{{ .Values.mongodbImages.repo }}",
                  "imageName": "{{ .Values.mongodbImages.imageName }}",
                  "tags": {
                    "mongodb5": "{{ .Values.mongodbImages.tags.mongodb5 }}",
                    "mongodb6": "{{ .Values.mongodbImages.tags.mongodb6 }}",
                    "mongodb7": "{{ .Values.mongodbImages.tags.mongodb7 }}"
                  }
                }
          volumeMounts:
            - name: log-volume
              mountPath: /logs
            - name: dump-volume
              mountPath: /dumps
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: pre-upgrade-log-pvc
        - name: dump-volume
          persistentVolumeClaim:
            claimName: pre-upgrade-dump-pvc
      {{- if .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- range $sec := .Values.images.pullSecrets }}
        - name: {{ $sec | quote }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 0
