{{/* Setting defaults if they are omitted. */}}
{{- $customRegistryEnabled := .Values.customeRegistryEnabled | default false }}
{{- $pxBackupEnabled := .Values.pxbackup.enabled | default false }}
{{- if eq $pxBackupEnabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: px-backup-account
  namespace: {{ .Values.namespace }} 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: px-backup-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: px-backup-role-binding
subjects:
- kind: ServiceAccount
  name: px-backup-account
  namespace: {{ .Values.namespace }} 
roleRef:
  kind: ClusterRole
  name: px-backup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: px-backup
  name: px-backup
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - protocol: TCP
    port: 10002
    targetPort: 10002
    name: grpc
  - protocol: TCP
    port: 10001
    targetPort: 10001
    name: rest-api
  selector:
    app: px-backup
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: px-backup
  namespace: {{ .Values.namespace }} 
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
     app: px-backup
  template:
    metadata:
      labels:
        app: px-backup
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeAffinityKey }}
                operator: NotIn
                values:
                - "{{ .Values.nodeAffinityValue }}"
      containers:
      - env:
        - name: SECRET_NAMESPACE
          value: {{ .Values.namespace }}
        - name: PX_BACKUP_DEFAULT_ORG
          value: {{ .Values.pxbackup.orgName }}
        image: {{ printf "%s/%s/%s:%s" .Values.dockerRegistryURL .Values.dockerImageRepoName .Values.pxBackupImage.imageName .Values.pxBackupImage.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: px-backup
        ports:
        - containerPort: 10002
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 10001
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 10001
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 60
        command:
        - /px-backup
        - start
        - --datastoreEndpoints=etcd:http://px-backup-etcd-0.px-backup-etcd-headless:2379,etcd:http://px-backup-etcd-1.px-backup-etcd-headless:2379,etcd:http://px-backup-etcd-2.px-backup-etcd-headless:2379
      serviceAccountName: px-backup-account
      imagePullSecrets:
        - name: docregistry-secret
---
{{- end -}}