{{/* Setting defaults if they are omitted. */}}
{{- $customRegistryEnabled := .Values.customeRegistryEnabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: pxcentral-lh-middleware
  namespace: {{ .Values.namespace }} 
  labels:
    run: pxcentral-lh-middleware
{{- include "px-backup.labels" . | nindent 4 }}
spec:
  selector:
    run: pxcentral-lh-middleware
  ports:
    - name: http
      port: 8091
      targetPort: 8091
      protocol: TCP
    - name: https
      port: 8092
      targetPort: 8092
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxcentral-lh-middleware
  namespace: {{ .Values.namespace }} 
  labels:
{{- include "px-backup.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      run: pxcentral-lh-middleware
  replicas: 1
  minReadySeconds: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: pxcentral-lh-middleware
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeAffinityKey }}
                operator: NotIn
                values:
                - "{{ .Values.nodeAffinityValue }}"
      containers:
      - name: pxcentral-lighthouse-backend
        image: {{ printf "%s/%s/%s:%s" .Values.dockerRegistryURL .Values.dockerImageRepoName .Values.images.pxcentralMiddlewareImage.imageName .Values.images.pxcentralMiddlewareImage.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: PX_NAMESPACE
            value: {{ .Values.namespace }} 
        ports:
          - name: http
            containerPort: 8091
          - name: https
            containerPort: 8092
      {{- if eq $customRegistryEnabled true }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      restartPolicy: Always
