{{- if .Values.awsMarketplace }}
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: px-aws-secret
type: Opaque
stringData:
  product-id: {{ template "px.getProductID" .}}
{{- end }}
