{{- $secretType := .Values.secretType | default "k8s" }}

{{- if eq $secretType "k8s" }}
{{- $namespace := "portworx" }}
{{- $existingNamespace := lookup "v1" "Namespace" "" $namespace }}

{{- if not $existingNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
{{- end -}}
{{- end -}}

