{{- $AKSInstall := .Values.AKSInstall | default false }}
{{- if $AKSInstall  }}
apiVersion: v1
data:
  AZURE_CLIENT_ID: {{ required "clientId is required for AKSInstall" .Values.provider.azure.clientId | quote }}
  AZURE_CLIENT_SECRET: {{ required "clientSecret is required for AKSInstall" .Values.provider.azure.clientSecret | quote }}
  AZURE_TENANT_ID: {{ required "tenantId is required for AKSInstall" .Values.provider.azure.tenantId | quote }}
kind: Secret
metadata:
  name: px-azure
  namespace: {{ template "px.getDeploymentNamespace" . }}
type: Opaque
{{- end }}