{{- $AKSInstall := .Values.AKSInstall | default false }}
{{- $azureClientId := .Values.provider.azure.clientId | default "none" }}
{{- $azureClientSecret := .Values.provider.azure.clientSecret | default "none" }}
{{- $azureTenantId := .Values.provider.azure.tenantId | default "none" }}
{{- if $AKSInstall  }}
apiVersion: v1
data:
  AZURE_CLIENT_ID: {{ required "clientId is required for AKSInstall" $azureClientId | quote }}
  {{- if ne $azureClientSecret "none"}}
  AZURE_CLIENT_SECRET: {{  $azureClientSecret | quote }}
  {{- end }}
  {{- if ne $azureTenantId "none" }}
  AZURE_TENANT_ID: {{ $azureTenantId | quote }}
  {{- end }}
kind: Secret
metadata:
  name: px-azure
  namespace: {{ template "px.getDeploymentNamespace" . }}
type: Opaque
{{- end }} 