{{ $vsphereUsername:= .Values.provider.vsphere.vsphereUsername | default "none" }}
{{ $vspherePassword:= .Values.provider.vsphere.vspherePassword | default "none" }}
{{- if and (ne $vsphereUsername "none") (ne $vspherePassword "none") }}
apiVersion: v1
kind: Secret
metadata:
  name: px-vsphere-secret
  namespace: {{ template "px.getDeploymentNamespace" . }}
type: Opaque
data:
  VSPHERE_PASSWORD: {{ toString $vspherePassword| quote }}
  VSPHERE_USER: {{ toString $vsphereUsername | quote }}
{{- end }}