{{- $customRegistryURL := .Values.customRegistryURL | default "none" }}

apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: px-hook-etcd-preinstall
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
{{ if ge .Capabilities.KubeVersion.Minor "8" }}
  backoffLimit: 0
{{ else }}
  activeDeadlineSeconds: 30
{{ end }}
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        terminationMessagePath: '/dev/termination-log'    
        terminationMessagePolicy: 'FallbackToLogsOnError'        
        imagePullPolicy: Always
        {{- if eq $customRegistryURL "none" }}
        image: "hrishi/px-etcd-preinstall-hook:v1"
        {{- else}}
        image: "{{ $customRegistryURL }}/hrishi/px-etcd-preinstall-hook:v1"
        {{- end}}
        command: ['/bin/sh']
        args: ['/usr/bin/etcdStatus.sh',"{{ .Values.etcdEndPoint }}"]
