{{- $isOpenshiftCluster := .Capabilities.APIVersions.Has "apps.openshift.io/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: px-backup-alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  alertmanagerConfigSelector:
    matchLabels:
      app: px-backup-alert-configs
  replicas: {{ .Values.pxbackup.alertmanager.replicas }}
  retention: {{ .Values.pxbackup.alertmanager.retention}}
  containers:
    - args:
        - '--config.file=/etc/alertmanager/config_out/alertmanager.env.yaml'
        - '--storage.path=/alertmanager'
        - '--data.retention={{ .Values.pxbackup.alertmanager.retention }}'
        - '--cluster.listen-address=[$(POD_IP)]:9094'
        - '--web.listen-address=:9093'
        - '--web.route-prefix=/'
        - '--cluster.label={{ .Release.Namespace }}/px-backup-alertmanager'
        - '--cluster.peer=alertmanager-px-backup-alertmanager-0.alertmanager-operated:9094'
        - '--cluster.peer=alertmanager-px-backup-alertmanager-1.alertmanager-operated:9094'
        - '--cluster.reconnect-timeout=5m'
        - '--web.config.file=/etc/alertmanager/web_config/web-config-custom.yaml'
      env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: pxc-backup-metrics
              key: metrics-token
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      image: {{ printf "%s/%s/%s:%s" .Values.images.pxBackupAlertmanagerImage.registry .Values.images.pxBackupAlertmanagerImage.repo .Values.images.pxBackupAlertmanagerImage.imageName .Values.images.pxBackupAlertmanagerImage.tag }}
      name: alertmanager
      ports:
        - containerPort: 9093
          name: web
          protocol: TCP
    - args:
      - --listen-address=:8080
      - --reload-url=http://$(USERNAME):$(PASSWORD)@localhost:9093/-/reload
      - --config-file=/etc/alertmanager/config/alertmanager.yaml.gz
      - --config-envsubst-file=/etc/alertmanager/config_out/alertmanager.env.yaml
      - --watched-dir=/etc/alertmanager/config
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            key: metrics-username
            name: pxc-backup-metrics
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            key: metrics-password
            name: pxc-backup-metrics
      name: config-reloader
      ports:
      - containerPort: 8080
        name: reloader-web
        protocol: TCP
  {{- if $isOpenshiftCluster }}
  {{- else }}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  {{- end }}
  listenLocal: true
  volumeMounts:
    - mountPath: /etc/alertmanager/web_config/web-config-custom.yaml
      name: web-config-custom
      readOnly: true
      subPath: web-config-custom.yaml
  volumes:
    - name: web-config-custom
      secret:
        defaultMode: 420
        secretName: pxc-backup-metrics
  {{- if .Values.persistentStorage.storageClassName }}
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.persistentStorage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistentStorage.prometheus.storage }}
  {{- end }}
