persistentStorage:
  enabled: false
  storageClassName:

storkRequired: false

oidc:
  centralOIDC:
    enabled: true
    defaultUsername: admin
    defaultPassword: admin
    defaultEmail: admin@portworx.com
    keyCloakBackendPassword: keycloak
    clientId: "pxcentral"
    clientSecret: "dummy"

  externalOIDC:
    enabled: false
    clientID:
    clientSecret:
    endpoint:

pxbackup:
  enabled: true
  orgName: default
  externalAccessHttpPort: 31234

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true

images:
  pullSecrets:
    - docregistry-secret
  pullPolicy: Always

  pxcentralApiServerImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-api
    tag: 1.0.4-dev
  pxcentralFrontendImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-ui-frontend
    tag: dev
  pxcentralBackendImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-ui-backend
    tag: dev
  pxcentralMiddlewareImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-ui-lhbackend
    tag: 1.1.1
  pxBackupImage:
    registry: docker.io
    repo: portworx
    imageName: px-backup-base
    tag: 1.0-dev
  postInstallSetupImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-post-setup
    tag: 1.0.4-dev
  etcdImage:
    registry: docker.io
    repo: bitnami
    imageName: etcd
    tag: 3.4.7-debian-10-r14
  keycloakBackendImage:
    registry: docker.io
    repo: bitnami
    imageName: postgresql
    tag: 11.7.0-debian-10-r9
  keycloakFrontendImage:
    registry: docker.io
    repo: jboss
    imageName: keycloak
    tag: 9.0.2
  keycloakLoginThemeImage:
    registry: docker.io
    repo: portworx
    imageName: keycloak-login-theme
    tag: 1.0.1
  keycloakInitContainerImage:
    registry: docker.io
    repo: library
    imageName: busybox
    tag: 1.31
  mysqlImage:
    registry: docker.io
    repo: library
    imageName: mysql
    tag: 5.7.22
